uppercase 테스트 코드 작성
daddys-home/unit-test-1week-assignment pull request #1
Opened 2019-07-16 12:12 UTC by TS-iii

대문자 개수 세는 클래스에 대한 테스트 코드 작성

2019-07-16 13:56 UTC, JaewanHwang requested changes

2019-07-16 13:56 UTC, JaewanHwang commented on src/test/java/UpperCaseCounterTest.java
> +    public void 반겂울_전달했을_때_0을_리턴하는지에_대한_테스트() {
메소드명 반겂울->반값을

2019-07-16 13:57 UTC, JaewanHwang commented on src/test/java/UpperCaseCounterTest.java
> +    public void 반겂울_전달했을_때_0을_리턴하는지에_대한_테스트() {
각 테스트 메소드 위에 누가했는지 알 수 있게 주석으로 이름좀 달아주세요

2019-07-16 15:36 UTC, pyi7628 commented on src/test/java/UpperCaseCounterTest.java
> +    public void 반겂울_전달했을_때_0을_리턴하는지에_대한_테스트() {
오타 수정하시구 merge하면 좋을 것 같아요!

2019-07-17 00:24 UTC, TS-iii commented on src/test/java/UpperCaseCounterTest.java
> +    public void 반겂울_전달했을_때_0을_리턴하는지에_대한_테스트() {
수정했슴다

2019-07-17 07:05 UTC, JaewanHwang approved these changes

2019-07-17 07:07 UTC, merged